defmodule Helpdesk.Repo.Migrations.First do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      add(:ancestor_ids, {:array, :uuid}, null: false, default: [])
    end
  end

  def down do
    alter table(:tickets) do
      remove(:ancestor_ids)
    end
  end
end
